# -*- mode: python ; coding: utf-8 -*-


import os

project_root = os.path.abspath('.')

a = Analysis(
    ['backend/app/main.py'],
    pathex=[project_root],
    binaries=[],
    datas=[],
    hiddenimports=[
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.loops.asyncio',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.http.httptools_impl',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'apscheduler',
        'apscheduler.schedulers',
        'apscheduler.schedulers.asyncio',
        'apscheduler.triggers',
        'apscheduler.triggers.interval',
        'apscheduler.triggers.cron',
        'apscheduler.triggers.date',
        'apscheduler.executors',
        'apscheduler.executors.asyncio',
        'apscheduler.executors.pool',
        'apscheduler.jobstores',
        'apscheduler.jobstores.memory',
        'backend',
        'backend.app',
        'backend.app.core',
        'backend.app.core.config',
        'backend.app.core.database',
        'backend.app.schemas',
        'backend.app.schemas.models',
        'backend.app.services',
        'backend.app.services.background_tasks',
        'backend.app.services.eport_client',
        'backend.app.services.exporter',
        'backend.app.services.extractor',
        'backend.app.services.image_extractor',
        'backend.app.api',
        'backend.app.api.bookings',
        'backend.app.api.collections',
        'backend.app.api.color_rules',
        'backend.app.api.containers',
        'backend.app.api.dashboard',
        'backend.app.api.export_backup',
        'backend.app.api.settings',
        'backend.app.api.vessels',
        'pdfplumber',
        'openpyxl',
        'pandas',
        'pydantic',
        'fastapi',
        'requests',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='backend_app',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='backend_app',
)
